# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4f7d5a018d653a5414cedd56ba12fd24f80afcd541a85d628cbc021c92d616c8afe20b910b3d50c48db01180bbd48f17ecaa088628d7883ebb352cf4a8677bc

test:
  secret_key_base: 8cdd668a96bbf733dd93c73b94f1d4f7418b1a09257aa2c70cd2e79ffafcc3ada776bfa4175a2107060621cfbb562a42ab4a92418e8d1e5e00f7155413842755

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
